import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es/shopify-marcas-cpg"
export const metadata: Metadata = { title: "Shopify para marcas CPG y de alimentos | LIVV", description: "Diseño y desarrollo Shopify para marcas CPG, alimentos, bebidas y productos de consumo en LATAM y España.", alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg/shopify", "x-default": "/cpg/shopify" } } }
const faq = [
  { q: "¿Por qué Shopify funciona bien para CPG?", a: "Porque permite lanzar rápido, manejar catálogo y promociones, integrar pagos y logística, y escalar el storefront sin reconstruir toda la operación." },
  { q: "¿Pueden diseñar algo que no parezca una plantilla?", a: "Sí. Diseñamos el sistema visual y la experiencia alrededor de la marca, manteniendo Shopify como motor de ecommerce." },
  { q: "¿Hacen bundles y suscripciones?", a: "Sí. Podemos estructurar packs, bundles, cross-sell, suscripciones y recorridos de recompra según el producto." },
]
const service = buildServiceJsonLd({ name: "Shopify para marcas CPG", slug: "shopify-marcas-cpg", url: `${SITE_URL}${path}`, description: "Diseño y desarrollo Shopify para marcas CPG y productos de consumo." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg/es` }, { name: "Shopify para CPG", url: `${SITE_URL}${path}` }])
export default function Page() { return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="Shopify · DTC · CPG" title="Shopify para marcas de consumo que quieren vender sin perder identidad." intro="Diseñamos y desarrollamos tiendas Shopify para marcas CPG con foco en producto, mobile, bundles, recompra y una experiencia visual que no se sienta genérica." facts={[{ label: "Plataforma", value: "Shopify" }, { label: "Categorías", value: "Alimentos · bebidas · belleza · consumo" }, { label: "Foco", value: "DTC · conversión · repetición de compra" }]} sections={[{ title: "Ecommerce que sigue hablando como la marca", body: <p>Usamos Shopify como infraestructura, no como lenguaje visual. El storefront se diseña alrededor del packaging, el producto, las ocasiones de consumo y las decisiones reales del cliente.</p> }, { title: "Capacidades", body: <ul className="list-disc space-y-2 pl-5"><li>Diseño y theme development.</li><li>PDPs, bundles y packs.</li><li>Suscripciones y recompra.</li><li>Landing pages de campaña.</li><li>Analytics, CRO y optimización mobile.</li></ul> }]} related={{ title: "Explorá el cluster", items: [{ href: "/cpg/es/ecommerce-marcas-consumo", name: "Ecommerce para marcas de consumo", description: "Más allá de Shopify: estrategia de conversión y arquitectura." }, { href: "/cpg/es/diseno-web-marcas-alimentos", name: "Diseño web para alimentos", description: "Brand storytelling y producto." }, { href: "/cpg/es/auditoria-digital", name: "Auditoría digital", description: "Priorizá qué corregir antes de reconstruir." }] }} faq={faq} /> }
