import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es/diseno-web-marcas-alimentos"
export const metadata: Metadata = { title: "Diseño web para marcas de alimentos | LIVV", description: "Diseño y desarrollo web para marcas de alimentos y productos de consumo. Ecommerce, storytelling de producto y retail readiness.", alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg/food-beverage", "x-default": "/cpg/food-beverage" } } }
const faq = [
  { q: "¿Qué debería tener la web de una marca de alimentos?", a: "Una propuesta clara, producto fácil de entender, ingredientes o beneficios cuando corresponda, puntos de venta, prueba social y un recorrido simple hacia compra o retail." },
  { q: "¿Pueden desarrollar ecommerce además del sitio de marca?", a: "Sí. Podemos combinar storytelling de marca y ecommerce en Shopify o en una solución a medida." },
  { q: "¿Trabajan con marcas nuevas y marcas ya instaladas?", a: "Sí. El alcance cambia según el momento: lanzamiento, expansión de catálogo, entrada a retail o rediseño." },
]
const service = buildServiceJsonLd({ name: "Diseño web para marcas de alimentos", slug: "diseno-web-marcas-alimentos", url: `${SITE_URL}${path}`, description: "Diseño web y ecommerce para marcas de alimentos y productos de consumo." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg/es` }, { name: "Marcas de alimentos", url: `${SITE_URL}${path}` }])
export default function Page() { return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="Alimentos · ecommerce · retail" title="Diseño web para marcas de alimentos que necesitan verse tan bien como saben." intro="Construimos sitios para marcas de alimentos que hacen simple entender el producto, confiar en la marca, descubrir sabores o variedades y pasar a compra o punto de venta sin fricción." facts={[{ label: "Ideal para", value: "Alimentos envasados · snacks · salsas · suplementos alimenticios" }, { label: "Objetivo", value: "Marca · ecommerce · retail" }, { label: "Stack", value: "Shopify · Next.js · Webflow · Framer" }]} sections={[{ title: "Producto primero", body: <p>La arquitectura parte de cómo compra la gente: qué es, qué sabor tiene, qué lo hace distinto, cómo se usa, dónde conseguirlo y qué variante elegir.</p> }, { title: "Qué solemos resolver", body: <ul className="list-disc space-y-2 pl-5"><li>Homepage y navegación de catálogo.</li><li>Páginas de producto y variedades.</li><li>Ingredientes, beneficios y uso.</li><li>Store locator y presencia en retail.</li><li>Ecommerce DTC y bundles.</li></ul> }]} related={{ title: "También puede servirte", items: [{ href: "/cpg/es/shopify-marcas-cpg", name: "Shopify para CPG", description: "Venta directa y catálogo de productos." }, { href: "/cpg/es/ecommerce-marcas-consumo", name: "Ecommerce para marcas de consumo", description: "CRO, mobile y experiencia de compra." }, { href: "/cpg/es/auditoria-digital", name: "Auditoría digital", description: "Detectar qué está frenando la conversión." }] }} faq={faq} /> }
