import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es/agencia-digital-cpg"
export const metadata: Metadata = { title: "Agencia digital CPG para LATAM y España | LIVV", description: "Partner digital para marcas CPG: estrategia, diseño web, Shopify, ecommerce, campañas y optimización para alimentos, bebidas y consumo.", alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg", "x-default": "/cpg" } } }
const faq = [
  { q: "¿Qué hace una agencia digital especializada en CPG?", a: "Conecta marca, producto, ecommerce y crecimiento: web, Shopify, campañas, lanzamientos, contenido y optimización orientados a cómo compra el consumidor." },
  { q: "¿Trabajan por proyecto o de forma mensual?", a: "Ambos. Podemos entrar con un sprint puntual y luego continuar como partner de crecimiento cuando la marca necesita iteración constante." },
  { q: "¿Pueden trabajar con equipos internos o agencias de branding?", a: "Sí. Podemos funcionar como capa digital y técnica junto a un equipo interno, estudio de branding o partner de performance." },
]
const service = buildServiceJsonLd({ name: "Agencia digital CPG", slug: "agencia-digital-cpg", url: `${SITE_URL}${path}`, description: "Partner digital para marcas CPG de Latinoamérica y España." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg/es` }, { name: "Agencia digital CPG", url: `${SITE_URL}${path}` }])
export default function Page() { return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="Partner digital · CPG · LATAM" title="Una agencia digital para marcas CPG que necesitan ejecutar rápido sin fragmentar el equipo." intro="Estrategia, diseño, desarrollo y ecommerce en un mismo partner para marcas de consumo que están lanzando, entrando a retail, expandiendo catálogo o profesionalizando su canal digital." facts={[{ label: "Modelo", value: "Sprint o partnership mensual" }, { label: "Capacidades", value: "Web · ecommerce · diseño · motion · growth" }, { label: "Mercados", value: "LATAM · España · US Hispanic" }]} sections={[{ title: "Menos handoffs, más continuidad", body: <p>El problema de muchas marcas chicas y medianas no es la falta de proveedores, sino tener demasiados. Unimos estrategia, diseño y ejecución digital para que el sitio, ecommerce, campañas y contenido avancen con un criterio común.</p> }, { title: "Dónde podemos entrar", body: <ul className="list-disc space-y-2 pl-5"><li>Lanzamiento o relanzamiento de marca.</li><li>Rediseño web y ecommerce.</li><li>Shopify y optimización de conversión.</li><li>Landings de campañas y retail.</li><li>Contenido visual y motion.</li><li>Soporte mensual de diseño y growth.</li></ul> }]} related={{ title: "Entradas posibles", items: [{ href: "/cpg/es/auditoria-digital", name: "Auditoría digital", description: "Empezar por diagnóstico y prioridades." }, { href: "/cpg/es/shopify-marcas-cpg", name: "Shopify para CPG", description: "Entrar por ecommerce y DTC." }, { href: "/cpg/es/diseno-web-marcas-alimentos", name: "Diseño web para alimentos", description: "Entrar por marca y producto." }] }} faq={faq} /> }
