import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es/ecommerce-marcas-consumo"
export const metadata: Metadata = { title: "Ecommerce para marcas de consumo y CPG | LIVV", description: "Estrategia, UX y desarrollo ecommerce para marcas de consumo, alimentos y bebidas. DTC, CRO, bundles y mobile.", alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg/ecommerce", "x-default": "/cpg/ecommerce" } } }
const faq = [
  { q: "¿Qué diferencia un ecommerce CPG de una tienda online genérica?", a: "La compra suele depender de entender rápido variantes, beneficios, tamaños, packs, reposición y confianza de marca. La arquitectura debe reflejar eso." },
  { q: "¿Trabajan conversión además del diseño?", a: "Sí. Revisamos navegación, PDP, mobile, bundles, cross-sell, recompra y medición para reducir fricción." },
  { q: "¿Pueden trabajar sobre una tienda existente?", a: "Sí. Podemos auditar y optimizar sin rehacer todo, o rediseñar cuando la estructura actual ya limita el crecimiento." },
]
const service = buildServiceJsonLd({ name: "Ecommerce para marcas de consumo", slug: "ecommerce-marcas-consumo", url: `${SITE_URL}${path}`, description: "Ecommerce y CRO para marcas CPG, alimentos, bebidas y productos de consumo." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg/es` }, { name: "Ecommerce", url: `${SITE_URL}${path}` }])
export default function Page() { return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="Ecommerce · DTC · CRO" title="Ecommerce para marcas de consumo que quieren convertir mejor, no solo vender online." intro="Diseñamos experiencias DTC alrededor de cómo se descubre, compara, prueba y vuelve a comprar un producto de consumo. Menos fricción, mejor mobile y una estructura preparada para campañas y crecimiento." facts={[{ label: "Foco", value: "DTC y conversión" }, { label: "Optimización", value: "Mobile · PDP · bundles · recompra" }, { label: "Mercados", value: "Argentina · LATAM · España" }]} sections={[{ title: "El ecommerce como parte del producto", body: <p>Para una marca CPG, la tienda no es un checkout pegado a la web. Es donde el cliente entiende variedades, arma un pack, descubre usos, compara y decide si vale la pena probar por primera vez.</p> }, { title: "Dónde ponemos el foco", body: <ul className="list-disc space-y-2 pl-5"><li>Arquitectura de catálogo y navegación.</li><li>Product detail pages.</li><li>Packs, bundles y cross-sell.</li><li>Mobile checkout y performance.</li><li>Recompra, suscripciones y CRM hooks.</li></ul> }]} related={{ title: "Servicios relacionados", items: [{ href: "/cpg/es/shopify-marcas-cpg", name: "Shopify para CPG", description: "Implementación sobre Shopify." }, { href: "/cpg/es/auditoria-digital", name: "Auditoría digital CPG", description: "Detectar fugas antes de rediseñar." }, { href: "/cpg/es/agencia-digital-cpg", name: "Agencia digital CPG", description: "Un partner más amplio para marca, web y growth." }] }} faq={faq} /> }
