import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es"
export const metadata: Metadata = {
  title: "Agencia digital para marcas CPG | Alimentos, bebidas y consumo | LIVV",
  description: "Diseño web, ecommerce, Shopify y estrategia digital para marcas CPG, alimentos, bebidas y productos de consumo en Latinoamérica y España.",
  alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg", "x-default": "/cpg" } },
  openGraph: { title: "LIVV para marcas CPG", description: "Web, ecommerce y crecimiento digital para marcas de consumo.", url: `${SITE_URL}${path}`, locale: "es_419" },
}
const faq = [
  { q: "¿Qué significa CPG?", a: "CPG significa Consumer Packaged Goods: productos de consumo envasados como alimentos, bebidas, cosmética, cuidado personal y otras categorías de compra frecuente." },
  { q: "¿Trabajan con marcas de Latinoamérica y España?", a: "Sí. LIVV trabaja en español e inglés con marcas de Argentina, Latinoamérica, España y Estados Unidos." },
  { q: "¿Hacen solo diseño web?", a: "No. Podemos cubrir estrategia digital, diseño, desarrollo, Shopify, ecommerce, contenido de lanzamiento, motion y optimización de conversión." },
  { q: "¿Pueden trabajar con una marca que ya tiene identidad y packaging?", a: "Sí. Podemos llevar un sistema de marca existente a una experiencia digital más sólida sin exigir un rebranding completo." },
]
const service = buildServiceJsonLd({ name: "Agencia digital para marcas CPG", alternateName: "Diseño web y ecommerce para marcas de consumo", slug: "cpg-es", url: `${SITE_URL}${path}`, description: "Diseño web, ecommerce y estrategia digital para marcas CPG, alimentos, bebidas y productos de consumo de Latinoamérica y España." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg` }, { name: "CPG en español", url: `${SITE_URL}${path}` }])

export default function Page() {
  return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="LIVV para marcas de consumo" title="Diseño, ecommerce y crecimiento digital para marcas CPG de habla hispana." intro="Ayudamos a marcas de alimentos, bebidas, belleza y productos de consumo a construir una presencia digital que esté a la altura del producto: clara para el cliente, sólida para retail y preparada para vender online." facts={[{ label: "Mercados", value: "Argentina · LATAM · España" }, { label: "Categorías", value: "Alimentos · Bebidas · Belleza · Consumo" }, { label: "Servicios", value: "Web · Shopify · Ecommerce · CRO · Lanzamientos" }, { label: "Idioma", value: "Español e inglés" }, { label: "Modelo", value: "Proyecto cerrado o partnership mensual" }, { label: "Enfoque", value: "Marca + producto + conversión" }]} sections={[{ title: "Una web que venda el producto antes de que el cliente lo pruebe", body: <p>En CPG la web tiene que explicar rápido qué hace distinto al producto, cómo se usa, por qué confiar en la marca, dónde comprar y qué probar después. Diseñamos esa experiencia alrededor de la decisión de compra, no alrededor de una plantilla.</p> }, { title: "Qué podemos construir", body: <ul className="list-disc space-y-2 pl-5"><li>Sitios de marca y lanzamientos.</li><li>Tiendas Shopify y ecommerce DTC.</li><li>Páginas de producto, bundles y suscripciones.</li><li>Secciones para retail, distribuidores y mayoristas.</li><li>Landings de campaña y contenido de lanzamiento.</li><li>Auditorías UX/CRO y rediseños.</li></ul> }, { title: "CPG en español también se busca con otras palabras", body: <p>Por eso el cluster no depende solo de la sigla CPG. También atacamos búsquedas relacionadas con marcas de alimentos, bebidas, productos de consumo, ecommerce para marcas y diseño web especializado por industria.</p> }]} related={{ title: "Servicios para marcas de consumo", items: [{ href: "/cpg/es/diseno-web-marcas-alimentos", name: "Diseño web para marcas de alimentos", description: "Webs pensadas para producto, confianza y conversión." }, { href: "/cpg/es/shopify-marcas-cpg", name: "Shopify para marcas CPG", description: "Ecommerce DTC para marcas de consumo." }, { href: "/cpg/es/ecommerce-marcas-consumo", name: "Ecommerce para marcas de consumo", description: "Arquitectura, CRO y experiencia de compra." }, { href: "/cpg/es/marcas-bebidas", name: "Diseño web para marcas de bebidas", description: "Flavor storytelling, retail y venta directa." }, { href: "/cpg/es/auditoria-digital", name: "Auditoría digital CPG", description: "Detectar los problemas antes del rediseño." }, { href: "/cpg", name: "CPG services in English", description: "Versión internacional del vertical." }] }} faq={faq} ctaLead="Contanos qué producto venden, dónde está hoy la marca y cuál es el próximo objetivo: lanzamiento, ecommerce, retail, expansión o rediseño." />
}
