import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es/marcas-bebidas"
export const metadata: Metadata = { title: "Diseño web para marcas de bebidas | LIVV", description: "Diseño web y ecommerce para marcas de bebidas: producto, sabores, retail, DTC y lanzamiento.", alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg/beverage", "x-default": "/cpg/beverage" } } }
const faq = [
  { q: "¿Trabajan específicamente con marcas de bebidas?", a: "Sí. La estructura se diseña alrededor de sabores, ocasiones de consumo, formatos, packs, retail y venta directa." },
  { q: "¿Pueden manejar múltiples sabores y SKUs?", a: "Sí. Diseñamos sistemas flexibles para líneas de producto, packs, ediciones y nuevas variantes." },
  { q: "¿Pueden integrar store locator?", a: "Sí. Podemos sumar puntos de venta, retail partners y llamadas a compra online según el modelo comercial." },
]
const service = buildServiceJsonLd({ name: "Diseño web para marcas de bebidas", slug: "marcas-bebidas", url: `${SITE_URL}${path}`, description: "Diseño web y ecommerce para marcas de bebidas y productos CPG." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg/es` }, { name: "Marcas de bebidas", url: `${SITE_URL}${path}` }])
export default function Page() { return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="Bebidas · DTC · retail" title="Diseño web para marcas de bebidas que necesitan vender el sabor antes del primer sorbo." intro="Construimos sitios y ecommerce para bebidas con foco en producto, sabores, ocasiones de consumo, packs, presencia en retail y una experiencia mobile que convierta." facts={[{ label: "Categorías", value: "Bebidas funcionales · café · mixers · soft drinks · bebidas premium" }, { label: "Foco", value: "Producto · retail · DTC" }, { label: "Plataformas", value: "Shopify · Next.js · custom" }]} sections={[{ title: "Hacer tangible lo que todavía no se probó", body: <p>La web tiene que convertir atributos difíciles de transmitir —sabor, textura, ocasión, energía, ritual— en una historia clara y visual que empuje a comprar o buscar el producto en retail.</p> }, { title: "Qué suele incluir", body: <ul className="list-disc space-y-2 pl-5"><li>Arquitectura por sabores y formatos.</li><li>Packs y bundles.</li><li>Store locator y retail proof.</li><li>Storytelling de producto.</li><li>Campañas y lanzamientos.</li></ul> }]} related={{ title: "Seguí explorando", items: [{ href: "/cpg/es/shopify-marcas-cpg", name: "Shopify para marcas CPG", description: "Venta directa y recompra." }, { href: "/cpg/es/diseno-web-marcas-alimentos", name: "Diseño web para alimentos", description: "Otro vertical fuerte dentro de CPG." }, { href: "/cpg/es/auditoria-digital", name: "Auditoría digital", description: "Priorizá cambios antes del rediseño." }] }} faq={faq} /> }
