import type { Metadata } from "next"
import { CpgLanding } from "@/components/seo/cpg-landing"
import { buildBreadcrumbsJsonLd, buildFaqJsonLd, buildServiceJsonLd, SITE_URL } from "@/lib/seo/structured-data"

const path = "/cpg/es/auditoria-digital"
export const metadata: Metadata = { title: "Auditoría digital para marcas CPG | LIVV", description: "Auditoría de web, ecommerce, mobile, producto y retail readiness para marcas CPG de Latinoamérica y España.", alternates: { canonical: path, languages: { "es-419": path, "es-ES": path, "en-US": "/cpg/digital-audit", "x-default": "/cpg/digital-audit" } } }
const faq = [
  { q: "¿Qué analiza la auditoría?", a: "Claridad de marca y producto, homepage, navegación, mobile, ecommerce, PDPs, retail readiness, contenido y medición." },
  { q: "¿Sirve si todavía no quiero rediseñar?", a: "Sí. La auditoría prioriza mejoras para que el equipo pueda implementar internamente o decidir con evidencia si hace falta rediseñar." },
  { q: "¿Puede convertirse en un proyecto con LIVV?", a: "Sí. Si tiene sentido, usamos el diagnóstico como brief para un sprint de mejora o rediseño." },
]
const service = buildServiceJsonLd({ name: "Auditoría digital para marcas CPG", slug: "auditoria-digital-cpg", url: `${SITE_URL}${path}`, description: "Auditoría UX, ecommerce y retail readiness para marcas de consumo." })
const crumbs = buildBreadcrumbsJsonLd([{ name: "Inicio", url: SITE_URL }, { name: "CPG", url: `${SITE_URL}/cpg/es` }, { name: "Auditoría digital", url: `${SITE_URL}${path}` }])
export default function Page() { return <CpgLanding lang="es" jsonLd={[service, buildFaqJsonLd(faq), crumbs]} kicker="Diagnóstico · UX · conversión" title="Detectá qué está frenando la presencia digital de tu marca CPG antes de rediseñar." intro="Revisamos la web como una góndola digital: qué entiende el cliente, dónde pierde confianza, qué le cuesta comprar y qué señales faltan para que la marca se vea preparada para crecer." facts={[{ label: "Analizamos", value: "Marca · UX · ecommerce · retail readiness" }, { label: "Resultado", value: "Prioridades concretas y accionables" }, { label: "Uso", value: "Implementar internamente o con LIVV" }]} sections={[{ title: "No es un checklist genérico", body: <p>Buscamos problemas específicos del negocio y los ordenamos por impacto: comprensión del producto, confianza, fricción mobile, PDP, packs, puntos de venta, contenido y medición.</p> }, { title: "Áreas de revisión", body: <ul className="list-disc space-y-2 pl-5"><li>Propuesta de valor y homepage.</li><li>Producto y catálogo.</li><li>Mobile y performance.</li><li>Ecommerce y conversión.</li><li>Retail, mayoristas y store locator.</li><li>Analytics y próximos tests.</li></ul> }]} related={{ title: "Después del diagnóstico", items: [{ href: "/cpg/es/ecommerce-marcas-consumo", name: "Optimización ecommerce", description: "Corregir los puntos de fuga del funnel." }, { href: "/cpg/es/diseno-web-marcas-alimentos", name: "Diseño web para alimentos", description: "Rediseño orientado a producto y marca." }, { href: "/cpg/es/agencia-digital-cpg", name: "Partner digital CPG", description: "Continuidad para campañas, lanzamientos y growth." }] }} faq={faq} /> }
